### ISSUE TITLE
dataset structure

### ISSUE THREAD

**Issue by danielzhangau** [tianyu0207/PEBAL#1]
Hi there, 

What is the structure of the datasets used in the code?
- /home/yu/yu_ssd/fishyscapes/
- /home/yu/anomaly_segment/
- /home/yu/yu_ssd/road_anomaly
- /home/yuyuan/work_space/fs_lost_and_found/

**Comment by tianyu0207** [comment]
Hi, Thanks for your interest in our work. 

We use the dataset structure downloaded from Synboost Github (https://github.com/giandbt/synboost)

**Comment by Matt-Dinh** [comment]
> Hi, Thanks for your interest in our work.
> 
> We use the dataset structure downloaded from Synboost Github (https://github.com/giandbt/synboost)
