### ISSUE TITLE
Question for Data prepration

### ISSUE THREAD

**Issue by hyunjunChhoi** [tianyu0207/PEBAL#11]
Could you provide the detail branch and folder path for the data ??

Also, there is lost and found dataloader class but there is no information about these data

I cannot understand the cityscape dataset preparation and also the fishyscape dataset

And the given processed cityscape and original cityscaped data , they should be in the same branch?

they have different name and branch ( cityscapes_processed , cityscapes) and also the processed data has no name left in file

but original data has the left.jpg  then, original cityscape data is not necessary ? 

However, dataloader load the named left.jpg I have trouble in data preparation . Could you help ? 

Thanks in advance

**Comment by yyliu01** [comment]
Hi,

You can alternatively download both preprocessed fishyscapes & cityscapes datasets [here](http://robotics.ethz.ch/~asl-datasets/Dissimilarity/data_processed.tar) (token from synboost GitHub)
