### ISSUE TITLE
data structure

### ISSUE THREAD

**Issue by chaoqinhuang** [tianyu0207/PEBAL#13]
Thank you for your great job and congratulations for ECCV oral!
I follow your guidance in another issue and download the processed data in [synboost](https://github.com/giandbt/synboost) but the data structure is different from your code.
For example, when I run ``python code/test.py`` and set ``C.city_root_path`` as ``'/GPFS/public/cityscapes_processed'``, I got an error:
``FileNotFoundError: [Errno 2] No such file or directory: '/GPFS/public/cityscapes_processed/images/city_gt_fine/val' ``.
You know because these are the proceed files, it is harder for us to understand the data structure.
Could you tell us how to reorganize the files downloaded from synboost. Or provide us the correct data structure like this:
```
./PEBAL
  ├── cityscapes_processed                               # dataset files
  │   ├── original
  │   ├── labels                 
  │   └── semantic
  ```
Thank you again and hope for your response!

**Comment by yyliu01** [comment]
Hi,

Thanks for your interest, and congratulations for your ECCV oral as well!

I apologise for the confusion of the data set structure, and I print the tree structures for them below.

1) For the training datasets (including both cityscapes, and coco),
```shell
city_scape/
├── annotation
│   └── city_gt_fine
│       ├── train
│       └── val
└── images
    └── city_gt_fine
        ├── train
        └── val
coco/
├── annotations
│   └── ood_seg_train2017
└── train2017
```
2) For the validation datasets,
```shell
fishyscapes/
├── LostAndFound
│   ├── entropy
│   ├── labels
│   ├── labels_with_ROI
│   ├── logit_distance
│   ├── mae_features
│   ├── original
│   ├── semantic
│   └── synthesis
└── Static
    ├── entropy
    ├── labels
    ├── labels_with_ROI
    ├── logit_distance
    ├── mae_features
    ├── original
    └── semantic

road_anomaly/
├── entropy
├── labels
├── mae_features
├── original
├── semantic
└── synthesis

lost_and_found/
├── gtCoarse
│   ├── test
│   │   ├── 02_Hanns_Klemm_Str_44
│   │   ├── 04_Maurener_Weg_8
│   │   ├── 05_Schafgasse_1
│   │   ├── 07_Festplatz_Flugfeld
│   │   └── 15_Rechbergstr_Deckenpfronn
│   └── train
│       ├── 01_Hanns_Klemm_Str_45
│       ├── 03_Hanns_Klemm_Str_19
│       ├── 06_Galgenbergstr_40
│       ├── 10_Schlossberg_9
│       ├── 11_Parkplatz_Flugfeld
│       ├── 12_Umberto_Nobile_Str
│       ├── 13_Elly_Beinhorn_Str
│       └── 14_Otto_Lilienthal_Str_24
└── leftImg8bit
    ├── test
    │   ├── 02_Hanns_Klemm_Str_44
    │   ├── 04_Maurener_Weg_8
    │   ├── 05_Schafgasse_1
    │   ├── 07_Festplatz_Flugfeld
    │   └── 15_Rechbergstr_Deckenpfronn
    └── train
        ├── 01_Hanns_Klemm_Str_45
        ├── 03_Hanns_Klemm_Str_19
        ├── 06_Galgenbergstr_40
        ├── 10_Schlossberg_9
        ├── 11_Parkplatz_Flugfeld
        ├── 12_Umberto_Nobile_Str
        ├── 13_Elly_Beinhorn_Str
        └── 14_Otto_Lilienthal_Str_24

```

I'll also put these structures in the [installation](https://github.com/tianyu0207/PEBAL/blob/main/docs/installation.md) file.
Hope it helps.

Best,
Yuyuan

**Comment by chaoqinhuang** [comment]
I have successfully run the codes. Many thanks to you!

**Comment by WuShuang1998** [comment]
> Hi,
> 
> Thanks for your interest, and congratulations for your ECCV oral as well!
> 
> I apologise for the confusion of the data set structure, and I print the tree structures for them below.
> 
> 1. For the training datasets (including both cityscapes, and coco),
> 
> ```shell
> city_scape/
> ├── annotation
> │   └── city_gt_fine
> │       ├── train
> │       └── val
> └── images
>     └── city_gt_fine
>         ├── train
>         └── val
> coco/
> ├── annotations
> │   └── ood_seg_train2017
> └── train2017
> ```
> 
> 2. For the validation datasets,
> 
> ```shell
> fishyscapes/
> ├── LostAndFound
> │   ├── entropy
> │   ├── labels
> │   ├── labels_with_ROI
> │   ├── logit_distance
> │   ├── mae_features
> │   ├── original
> │   ├── semantic
> │   └── synthesis
> └── Static
>     ├── entropy
>     ├── labels
>     ├── labels_with_ROI
>     ├── logit_distance
>     ├── mae_features
>     ├── original
>     └── semantic
> 
> road_anomaly/
> ├── entropy
> ├── labels
> ├── mae_features
> ├── original
> ├── semantic
> └── synthesis
> 
> lost_and_found/
> ├── gtCoarse
> │   ├── test
> │   │   ├── 02_Hanns_Klemm_Str_44
> │   │   ├── 04_Maurener_Weg_8
> │   │   ├── 05_Schafgasse_1
> │   │   ├── 07_Festplatz_Flugfeld
> │   │   └── 15_Rechbergstr_Deckenpfronn
> │   └── train
> │       ├── 01_Hanns_Klemm_Str_45
> │       ├── 03_Hanns_Klemm_Str_19
> │       ├── 06_Galgenbergstr_40
> │       ├── 10_Schlossberg_9
> │       ├── 11_Parkplatz_Flugfeld
> │       ├── 12_Umberto_Nobile_Str
> │       ├── 13_Elly_Beinhorn_Str
> │       └── 14_Otto_Lilienthal_Str_24
> └── leftImg8bit
>     ├── test
>     │   ├── 02_Hanns_Klemm_Str_44
>     │   ├── 04_Maurener_Weg_8
>     │   ├── 05_Schafgasse_1
>     │   ├── 07_Festplatz_Flugfeld
>     │   └── 15_Rechbergstr_Deckenpfronn
>     └── train
>         ├── 01_Hanns_Klemm_Str_45
>         ├── 03_Hanns_Klemm_Str_19
>         ├── 06_Galgenbergstr_40
>         ├── 10_Schlossberg_9
>         ├── 11_Parkplatz_Flugfeld
>         ├── 12_Umberto_Nobile_Str
>         ├── 13_Elly_Beinhorn_Str
>         └── 14_Otto_Lilienthal_Str_24
> ```
> 
> I'll also put these structures in the [installation](https://github.com/tianyu0207/PEBAL/blob/main/docs/installation.md) file. Hope it helps.
> 
> Best, Yuyuan

So I need write a script to reorganize the files? Thanks.
