### ISSUE TITLE
Having issues in model training 

### ISSUE THREAD

**Issue by yzpick** [tianyu0207/PEBAL#14]
Hi, thanks for the fantastic work. But I have some issues in model training, I prepared the dataset according to the instructions, but got this error:
  0%|                                                                                                            | 0/818 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/xxxx/xxxx/xxxx/PEBAL/code/main.py", line 158, in <module>
    main(-1, 1, config=config, args=args)
  File "/home/xxxx/xxxx/xxxx/PEBAL/code/main.py", line 113, in main
    trainer.train(model=model, epoch=curr_epoch, train_sampler=train_sampler, train_loader=train_loader,
  File "/home/xxxx/xxxx/xxxx/PEBAL/code/engine/trainer.py", line 47, in train
    target = minibatch['label'].cuda(non_blocking=True)
KeyError: 'label'

Process finished with exit code 1
_______________
I print out the minibatch and found it doesn't have the label field:
{'data': tensor([[[[-0.0116, -0.0116, -0.0116,  ..., -1.6727, -1.6727, -1.6555],
          [-0.0116, -0.0116, -0.0116,  ..., -1.6555, -1.6727, -1.6555],
          [-0.0287, -0.0116, -0.0116,  ..., -1.6555, -1.6555, -1.6384],
          ...,
          ...,
          [-0.5844, -0.6367, -0.6367,  ..., -0.6193, -0.6193, -0.6018],
          [-0.5844, -0.6193, -0.6193,  ..., -0.6367, -0.6193, -0.6018],
          [-0.5844, -0.5844, -0.6018,  ..., -0.6367, -0.6367, -0.6193]]]]), 'fn': ['dusseldorf_000206_000019', 'dusseldorf_000144_000019', 'tubingen_000062_000019', 'hamburg_000000_089696', 'dusseldorf_000035_000019_unknown_unknown', 'erfurt_000072_000019', 'hamburg_000000_049558', 'bremen_000118_000019'], 'n': tensor([6545, 6545, 6545, 6545, 6545, 6545, 6545, 6545]), 'is_ood': tensor([False, False, False, False, False, False, False, False])}
______
What files should be include in the annotation files? I put the original files from cityscape and the generated labeltrainids files there. Is there anything I did wrong? 

Thanks!
Thanks!

**Comment by yyliu01** [comment]
Thanks for your interest!

Could you please double check your code that fetching the label in this [line](https://github.com/tianyu0207/PEBAL/blob/21ed4964f76fb92a12adafe0944925bca9dfbdb4/code/dataset/data_loader.py#L715). 

Also, could you please check your cityscapes architecture. 

It should following the tree graph below:

```shell
city_scape/
├── annotation
│   └── city_gt_fine
│       ├── train
│       └── val
└── images
    └── city_gt_fine
        ├── train
        └── val
```

**Comment by yzpick** [comment]
Yes I followed the instructions to make the dataset and it has the exactly same tree graph view.. and images can be loaded but not gt files; and I can also infer my own images to get results. So it should be the gt loading issue.
Not sure if I misunderstood anything, but seems the self.target has a hard coded gt file name style as 'gtFine.png' but all annotation files from cityscape have different ending names like _labelTrainIds/labelIds etc. It would be helpful if you could provide the expected file names under each folder in your tree graph. Just make sure my file names are correct. 

I tried to modify that ending name, it was able to process and load gt files, but only upto a point and then triggered new keyerror label errors....



Thanks!

**Comment by yyliu01** [comment]
Ah...  
I totally forget that, yes, we might have different target file name.

This is part of the label files' names for PEBAL training:

```shell
    ├── munster_000172_000019_gtFine_color.png
    ├── munster_000172_000019_gtFine_instanceIds.png
    ├── munster_000172_000019_gtFine_labelIds.png
    ├── munster_000172_000019_gtFine.png
    ├── munster_000172_000019_gtFine_polygons.json
    ├── munster_000173_000019_gtFine_color.png
    ├── munster_000173_000019_gtFine_instanceIds.png
    ├── munster_000173_000019_gtFine_labelIds.png
    ├── munster_000173_000019_gtFine.png
    └── munster_000173_000019_gtFine_polygons.json

```

Could you please correct the path based on your filename? Note: the file end with gtFine is what you are looking for (e.g., munster_000173_000019_gtFine.png).

**Comment by yzpick** [comment]
Thanks, but I didn't see any file in the annotation folder ends with gtfine.png, is the _labelTrainIds.png you used for gtfine.png?

**Comment by yyliu01** [comment]
@yzpick please download my label file in this [link](https://1drv.ms/u/s!AsvBenvUFxO3hx5Bpqyyx09evciC?e=l4E3o7).

**Comment by dahliau** [comment]
Can you explain what is the different between the annotations files? 
'*gtFine.png' vs '*gtFine_labelIds.png'
(Or how did you generate the '*gtFine.png' files?)

I was impressed by your work and want to implement it on my own dataset.
