### ISSUE TITLE
Is there a link to download the best checkpoints?

### ISSUE THREAD

**Issue by laodar** [tianyu0207/PEBAL#16]
Hi!
I am trying to find out some hard cases in RoadAnomaly. It will be very helpful to provide the best checkpoints. 
Could you provide a link to download them?
Thanks!

**Comment by yyliu01** [comment]
Please take a look for this [page](https://github.com/tianyu0207/PEBAL/blob/main/docs/before_start.md). We've provided the checkpoint in the **inference** section.
