### ISSUE TITLE
why larger aω means lower inlier free energy

### ISSUE THREAD

**Issue by luoyuchenmlcv** [tianyu0207/PEBAL#19]
Thanks for sharing your great work!

In the paper you mentioned that: aω = (−Eθ (x)ω )^2, 
but this is same as  aω = Eθ (x)ω ^2, but  larger aω means lower inlier free energy only happens when Eθ (x)ω <0, where can we confirm this condition ?

**Comment by tianyu0207** [comment]
> 

Hi Thanks for your interest in our work. As discussed in Eq. 4, the energy is computed as the negative of logsumexp, which means Eθ (x)ω <0.

**Comment by luoyuchenmlcv** [comment]
Thanks for your explaination, but why logsumexp is positive? 
If logsumexp is positive, it means sumexp > 1.
From wiki, [logsumxep](https://en.wikipedia.org/wiki/LogSumExp)
sumexp has lower bound exp{f(y, x)_max}, 
but there is no guarantee that f(y, x)_max >0, maybe empirically logsumexp is positive, how can we say logsumexp can be proven to be positive ?

I did a test with python code as follows:


import numpy as np
def logsumexp(x):
    return np.log(np.exp(x).sum())

x = [-10,-10,-10,-10]
print("exp", np.exp(x))
print("sumexp", np.exp(x).sum())
print("logsumexp", logsumexp(x))


it gives:
exp [4.53999298e-05 4.53999298e-05 4.53999298e-05 4.53999298e-05]
sumexp 0.00018159971904993942
logsumexp -8.61370563888011

logsumexp in this case is negative, which means Eθ (x)ω >0

**Comment by tianyu0207** [comment]
> 

Thanks for the thoughtful reply. there's no guarantee that the energy value is positive or negative. However, empirically we observe most of the values are negative, and also the energy is constrained by two negative margins m_in and m_out (-12 and -6) .
