### ISSUE TITLE
Typo of "WideResNet34"

### ISSUE THREAD

**Issue by devinxzhang** [tianyu0207/PEBAL#21]
Hi, thanks for your excellent work! I am wondering if this is a typo in your paper of the pretrained backbone. In your paper, it is claimed that the seg model is DeepLabv3+ with a WideResNet34 backbone. However, both the baseline "meta-OOD" and your code show "WideResNet38" is actually used. So I guess there must be a typo in your paper. 

Thanks again for your awesome work!

**Comment by tianyu0207** [comment]
> Hi, thanks for your excellent work! I am wondering if this is a typo in your paper of the pretrained backbone. In your paper, it is claimed that the seg model is DeepLabv3+ with a WideResNet34 backbone. However, both the baseline "meta-OOD" and your code show "WideResNet38" is actually used. So I guess there must be a typo in your paper.
> 
> Thanks again for your awesome work!

Thank you so much for spotting the typo. This has been addressed in the camera-ready version and Arxiv. Thanks again for your interest in our work.
