### ISSUE TITLE
cannot reproduce the result on "Lost And Found testing set"

### ISSUE THREAD

**Issue by devinxzhang** [tianyu0207/PEBAL#22]
Hi,

I use the provided model and could successfully reproduce the results on "cityscapes valid set", "Fishyscapes ls & Static", and "Road Anomaly". 

However, when it comes to "Lost And Found testing set", I get the following result:
AUROC score for LostAndFound: 0.9688811261819444 
AUPRC score for LostAndFound: 0.7222531717939171
FPR@TPR95 for LostAndFound: 0.1460461138717795

I have exactly the same data structure. I am not sure where goes wrong. Would you have any suggestions?

Thanks!

**Comment by tianyu0207** [comment]
> 

Because the appearance features of the LostAndFound Testing set and Fishyscape are so different, we have two different checkpoints for those two datasets, respectively. We haven't released the checkpoint of the LostAndFound testing set and will release it later.  Thanks so much for your interest.
