### ISSUE TITLE
离群点的像素是通过阈值筛选出来的吗？

### ISSUE THREAD

**Issue by Runist** [tianyu0207/PEBAL#25]
感谢作者开源的工作。
我看代码中没有对离群点的像素进行特定筛选，只提供了验证精度的代码和可视化的代码。plt.imshow()这个代码的归一化确实符合视觉上的预期，但我想知道你们是否有一个标准的阈值或是其他方法，可以单独获取离群点的像素。
另外我正在做的工作是基于对比检测的方式来识别离群点，不同的是，我训练和测试都采用Y+1类，最后通过Argmax来获取异物。我正在尝试将你们的loss添加到变化检测中，请问作者对这个loss的添加有什么建议么？

**Comment by tianyu0207** [comment]
> 感谢作者开源的工作。 我看代码中没有对离群点的像素进行特定筛选，只提供了验证精度的代码和可视化的代码。plt.imshow()这个代码的归一化确实符合视觉上的预期，但我想知道你们是否有一个标准的阈值或是其他方法，可以单独获取离群点的像素。 另外我正在做的工作是基于对比检测的方式来识别离群点，不同的是，我训练和测试都采用Y+1类，最后通过Argmax来获取异物。我正在尝试将你们的loss添加到变化检测中，请问作者对这个loss的添加有什么建议么？

是的  可以通过一个标准的阈值 您可以通过实验挑选一个最佳的阈值。  

最直接的方法 可以直接把pebal loss和contrastive loss 结合相加 然后观察下是否能提升准确性 每项loss前面可以加上不同hyperparameter来平衡。 

感谢对我们的工作感兴趣。

**Comment by Runist** [comment]
你好，您的邮件我已收到。我将在近期查看，尽快给你回复。

**Comment by skming666** [comment]
anomaly map  文章中这个是如何生成的，我在代码中没找到，请楼主指点下
