### ISSUE TITLE
Which deeplabv3+ checkpoint should I download?

### ISSUE THREAD

**Issue by Yang-Li-2000** [tianyu0207/PEBAL#28]
before_start.md states that it is necessary to download a deeplabv3+ checkpoint. However, there are many deeplabv3+ checkpoints. Which one should I download?

**Comment by tianyu0207** [comment]
> before_start.md states that it is necessary to download a deeplabv3+ checkpoint. However, there are many deeplabv3+ checkpoints. Which one should I download?

Hi, thanks for your interest. As mentioned in our readme the 'cityscape best' checkpoint from https://github.com/NVIDIA/semantic-segmentation/tree/sdcnet.
