### ISSUE TITLE
Doubt about Fishyscapes

### ISSUE THREAD

**Issue by matteosodano** [tianyu0207/PEBAL#31]
Hi,
thanks for your work! One quick question about the Fishyscapes dataset. Fishyscapes images are only for validation/testing, while training happens on Cityscapes? Or did I get anything wrong?

**Comment by tianyu0207** [comment]
> 

Hi, Thanks for your interests. You are right, the training only happens on Cityscapes.  Fishyscapes images are only for validation/testing.

**Comment by matteosodano** [comment]
Perfect, thanks!

**Comment by matteosodano** [comment]
Hello again, 
one other question about the dataset, to be sure I'm comparing fairly with what you did.

What did you exactly use (and how) of Fishyscapes? I see there's a folder with recordings from Stuttgart that come with images and labels, and they're divided into `train` and `test`. The `train` folder has 8 subfolders (Hanss Klemm Str, Galgenbergstr, Schlossberg, etc.), while the `test` folder has 5 subfolders (Hanss Klemm Str, Maurener Weg, Schafgasse, etc.).
What did you use and how?

My idea was that you used the `train` for validation, and `test` for testing, thus the number reported on the paper are the ones on the `test` split. Would that be correct?

Thank you again for your work. Good luck!

**Comment by yyliu01** [comment]
Hi @matteosodano,

Any of the data from Fishyscapes are not used for training.
Please find the processed OoD datasets in this [issue](https://github.com/yyliu01/RPL/issues/1).

Cheers,
Yuyuan
