### ISSUE TITLE
数据集对不上

### ISSUE THREAD

**Issue by tang576225574** [tianyu0207/PEBAL#32]
说明文档上说的数据集目录结构，和提供的数据集及其构造方法，均对不上，尝试多种方法，一直在报路径不对的错。关于数据集构建这一块，可以提供更详细的步骤和做法吗？

**Comment by yyliu01** [comment]
Hi @tang576225574 
Please use the [link](https://drive.google.com/drive/folders/1_5rZgWEDT9VbWch5dTkXWAOddUGqMmgE?usp=share_link) in here.

**Comment by tang576225574** [comment]
thanks
