### ISSUE TITLE
How to continue my training

### ISSUE THREAD

**Issue by Orange-rightperson** [tianyu0207/PEBAL#33]
I parse my trainnig and I notice there is a parser in the engine file containing continue args, how can I use this?

**Comment by Orange-rightperson** [comment]
And I find that when I use distributed training, the training will stop at the last batch . How can I solve this problem?

**Comment by yyliu01** [comment]
Hi @Orange-rightperson 

Sorry, dude, you'll probably have same feedback in [issue](https://github.com/yyliu01/RPL/issues/10).

Could you double check the data is same from this [link](https://drive.google.com/drive/u/0/folders/18qCyDfeVEeMtmGzPcXllQva_5NT-fTi1)?

Cheers,
Yuyuan

**Comment by Orange-rightperson** [comment]
@yyliu01  yes, the data is the same

**Comment by Orange-rightperson** [comment]
@yyliu01 Would you please tell me what to change when you begin distributed traning?

**Comment by yyliu01** [comment]
Hi @Orange-rightperson 

There is nothing to change except the ``gpus`` flag. Well, could you please send me an email, so that we can go through some details of your deployment.

**Comment by Orange-rightperson** [comment]
Hello,  thanks for your replying



---- Replied Message ----
| From | Yuyuan ***@***.***> |
| Date | 10/08/2023 14:27 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [tianyu0207/PEBAL] How to continue my training (Issue #33) |

Hi @Orange-rightperson

There is nothing to change except the gpus flag. Well, could you please send me an email, so that we can go through some details of your deployment.
