### ISSUE TITLE
How to get result of Initial Prediction and Final Prediction?

### ISSUE THREAD

**Issue by Matt-Dinh** [tianyu0207/PEBAL#5]
Hi, thank you for your great work.

I've gone through your repo but still had no idea how to get result of Initial Prediction (output of DeepWV3Plus segmentation) and Final Prediction (combined of Init Prediction and Anomaly Prediction ?). Could you please suggest me how to get them out? Thank you so much.

Best regards,

![Screenshot from 2022-07-07 08-50-23](https://user-images.githubusercontent.com/44317133/177675460-917fe7db-5736-4f91-aa11-8dc3aecd1eda.png)

**Comment by yyliu01** [comment]
Hi Matt,

Thanks for your interest. We follow the previous works (e.g., meta-ood), the _initial prediction_ is based on the pre-trained checkpoint that token from the NVIDIA GitHub, while after the training of pebal, we can have the _final prediction_ with an energy threshold to detect the discriminative region of the anomalies.

Best Regards,
Yuyuan

**Comment by Matt-Dinh** [comment]
Ok, I've got it. Thank you so much for your support.
