### ISSUE TITLE
inlier vs outlier

### ISSUE THREAD

**Issue by jyang68sh** [tianyu0207/PEBAL#6]
Hi I am bit confused with the definition of inlier and outlier classes described in your paper. 

e.g. For cityscapes, what are the inlier classes and outlier classes?

Thanks

**Comment by yyliu01** [comment]
Thanks for your interest. 

The inlier indicates the original 19 classes, while the outlier denotes the anomalous objects. 
In the Cityscapes dataset, there is **no outlier** (in case we ignore the 255 class). We follow the meta-ood to implement the outlier exposure (OE) to introduce the anomalous objects via extra training data (coco). There is a visualisation in Fig.2, Page 6 of our paper, which grabs the laptop from its original image to the driving scenes.

Regards,
Yuyuan

**Comment by yyliu01** [comment]
Closing the issue, but feel free to reopen.

**Comment by jyang68sh** [comment]
@

> Thanks for your interest.
> 
> The inlier indicates the original 19 classes, while the outlier denotes the anomalous objects. In the Cityscapes dataset, there is **no outlier** (in case we ignore the 255 class). We follow the meta-ood to implement the outlier exposure (OE) to introduce the anomalous objects via extra training data (coco). There is a visualisation in Fig.2, Page 6 of our paper, which grabs the laptop from its original image to the driving scenes.
> 
> Regards, Yuyuan

Hi. Thanks for your answer. I am still reading about your abstention learning module. Is it a kind of active learning?

**Comment by yyliu01** [comment]
@jyang68sh This work is based on the gambler loss (which belongs to abstention learning), and I don't think it is related to active learning. I recommend reading it (https://arxiv.org/abs/1907.00208) for a better understanding of the background.
