### ISSUE TITLE
Can you offer the fishyscapes and coco (for outlier exposures) datasets baidu netdisk for training?

### ISSUE THREAD

**Issue by liuxubit** [tianyu0207/PEBAL#7]
hello author, 
    Can you offer the fishyscapes and coco (for outlier exposures) datasets baidu netdisk for training?
   I don't know how to download the fishyscapes datasets from the website  and what is necessary for training.
   Thank you very much!

**Comment by yyliu01** [comment]
Hi,

I'm sorry that I'm currently not in China and uploading to the Baidu Netdisk is super slow (even I bought the VIP).

The fishyscape validation set can be downloaded here (https://fishyscapes.com/dataset), it only contains limited data so it won't cost you lots of time. Please note, the fishyscape is only used for validation and testing.

The COCO seems can be downloaded in here (https://blog.csdn.net/qq_43853414/article/details/104800356) via the Baidu Netdisk, but I didn't check its correctness.

For more details, I recommend reading the instruction docs (https://github.com/tianyu0207/PEBAL/blob/main/docs/installation.md).

Regards,
Yuyuan

**Comment by SnowdenLee** [comment]
Hi,
I'm wodering how to get Fishyscapes Static split [Fishyscapes Static](https://github.com/tianyu0207/PEBAL/blob/453d24138853d443439ee0f71fa35c69cd8b75bc/code/dataset/data_loader.py#L271)? From https://fishyscapes.com/dataset, only Lost&Found is available.
Thanks in advance!

**Comment by tianyu0207** [comment]
> 

Hi the Fishycapes Static should be just the 'FS Web Validation Data' on the fishyscape website. Also, you can use the processed images from Synboost using the link here.  http://robotics.ethz.ch/~asl-datasets/Dissimilarity/data_processed.tar
